-- VHDL Entity jtag_lib.counter.symbol
--
-- Created:
--          by - pdecher.UNKNOWN (ORW-PDECHER-LT)
--          at - 18:47:36 02/10/2009
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2008.1a (Build 9)
--
LIBRARY ieee;
    USE ieee.std_logic_1164.all;
    USE ieee.std_logic_arith.all;

ENTITY counter IS
   PORT( 
      clk   : IN     std_ulogic;
      rst_n : IN     std_ulogic;
      ld_n  : IN     std_ulogic;
      cen   : IN     std_ulogic;
      up_dn : IN     std_ulogic;
      din   : IN     std_ulogic_vector (7 DOWNTO 0);
      tc    : OUT    std_ulogic;
      zero  : OUT    std_ulogic;
      dout  : OUT    std_ulogic_vector (7 DOWNTO 0)
   );

-- Declarations

END counter ;

--
-- VHDL Architecture jtag_lib.counter.rtl
--
-- Created:
--          by - pdecher.UNKNOWN (ORW-PDECHER-LT)
--          at - 18:47:36 02/10/2009
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2008.1a (Build 9)
--

ARCHITECTURE rtl OF counter IS
   -- Architecture declarations
   signal count_s : unsigned(7 DOWNTO 0);   -- <<< JTAG_152
   signal top_count_s  : std_ulogic;
   signal zero_count_s : std_ulogic;
                        

BEGIN

   -----------------------------------------------------------------
   cnt_proc : PROCESS (clk, rst_n)
   -----------------------------------------------------------------
   BEGIN
      -- <<< JTAG_138
      IF  (rst_n = '0')   THEN
         -- This causes reset of the cntr
          count_s <= (others => '0');
      ELSIF  clk'event AND clk = '1' THEN
         IF  (ld_n = '0')  THEN
            count_s <= unsigned(din);
        
         ELSIF  (cen = '1' AND up_dn = '0') THEN
             -- <<< JTAG_143, JTAG_140
            count_s <= count_s - "0000001";
         ELSIF  (cen = '1' AND up_dn = '1') THEN
           
            count_s <= count_s + "00000001";
         END IF;
      END IF;
   END PROCESS cnt_proc;


-- Architecture concurrent statements
top_count_s  <= '1' WHEN (count_s = unsigned'("11111111")) ELSE '0';
zero_count_s <= '1' WHEN (count_s = unsigned'("00000000")) ELSE '0';
--** Output assignmnets
dout <= std_ulogic_vector(count_s);
tc   <= '1' when top_count_s = '1'  else '0';
zero <= '1' when zero_count_s = '1' else '0';

END rtl;
